#Task1
print("Task1")
f=open("new.txt","a")
a=input("Enter your name \n")
b=input("Enter your email\n")
c=input("Enter your contact\n")
f.write(f"Name={a} \n")
f.write(f"Email={b} \n")
f.write(f"Contact={c} \n")
f.close()
#Task2

f=open("new.txt","r")
print(f.read())
f.close()
#Task3
f=open("new.txt","a")
a=input("Enter your name \n")
b=input("Enter your email\n")
c=input("Enter your contact\n")
f.write(f"Name={a} \n")
f.write(f"Email={b} \n")
f.write(f"Contact={c} \n")
a=input("Enter your name \n")
b=input("Enter your email\n")
c=input("Enter your contact\n")
f.write(f"Name={a} \n")
f.write(f"Email={b} \n")
f.write(f"Contact={c} \n")
f.close()
f=open("new.txt","r")
print(f.read())
f.close()
